# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

project 'libPhoneNumber-Demo'

target 'libPhoneNumber-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for libPhoneNumber-Demo
  #pod 'libPhoneNumber-iOS', :git => 'https://github.com/iziz/libPhoneNumber-iOS'
  #pod 'libPhoneNumberGeocoding', :git => 'https://github.com/iziz/libPhoneNumber-iOS'
  #pod 'libPhoneNumberShortNumber', :git => 'https://github.com/iziz/libPhoneNumber-iOS'
  pod 'libPhoneNumber-iOS', :path => '../'
  pod 'libPhoneNumberGeocoding', :path => '../'
  pod 'libPhoneNumberShortNumber', :path => '../'

end
