# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo App
  pod 'libPhoneNumber-iOS'
  pod 'libPhoneNumberGeocoding', :git => 'https://github.com/iziz/libPhoneNumber-iOS'
  target 'Demo AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo AppUITests' do
    # Pods for testing
  end

end
