target 'libPhoneNumber-GeocodingParser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for libPhoneNumber-GeocodingParser
  pod 'SSZipArchive'
end
