name: Pull Request CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pull-request-ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    uses: ./.github/workflows/github-holodeck-trials.yml
    with:
      schemes: |
        libPhoneNumber
        libPhoneNumberGeocoding
        libPhoneNumberShortNumber
      xcode_container: libPhoneNumber.xcodeproj
      device_types: |
        iphone
    secrets: inherit

  podspec-lint:
    name: Podspec Linting
    uses: ./.github/workflows/github-podspec-sensor-sweep.yml
    with:
      podspecs: |
        libPhoneNumber-iOS.podspec
        libPhoneNumberGeocoding.podspec
        libPhoneNumberShortNumber.podspec
